[package]
name = "katex-dl"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
description = "KaTeX distribution downloader for vendoring purposes"
readme = "README.md"
repository.workspace = true
license.workspace = true

[dependencies]

[lints]
workspace = true

[profile.release]
workspace = true
