[package]
name = "ssg"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
description = "Static site generator for my personal website"
readme = "README.md"
repository.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
aho-corasick.workspace = true
anyhow.workspace = true
camino.workspace = true
common = { path = "../common/" }
ego-tree = "0.10.0"
foldhash = "0.1.4"
glob = "0.3.2"
gray_matter = { version = "0.2.8", default-features = false, features = ["yaml"] }
image = { version = "0.25.5", default-features = false, features = ["avif", "gif", "jpeg", "png", "webp"] }
include_dir = "0.7.4"
jiff = { version = "0.1.24", default-features = false, features = ["alloc", "serde", "std"] }
lightningcss = { version = "1.0.0-alpha.63", default-features = false, features = ["browserslist", "grid", "into_owned"] }
markup5ever = "0.14.0"
phf = { version = "0.11.3", features = ["macros"] }
pulldown-cmark = { version = "0.12.2", default-features = false, features = ["html", "simd"] }
rquickjs = { version = "0.8.1", features = ["parallel", "rust-alloc"] }
same-file = "1.0.6"
scraper = { version = "0.22.0", default-features = false, features = ["deterministic", "errors"] }
serde = "1.0.217"
syntect = { version = "5.2.0", default-features = false, features = ["default-syntaxes", "default-themes", "html", "regex-onig"] }
toml_edit = { version = "0.22.22", default-features = false, features = ["parse", "serde"] }

[lints]
workspace = true
