[package]
name = "ssg"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
description = "Static site generator for my personal website"
readme = "README.md"
repository.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
foldhash = "0.1.3"
gray_matter = { version = "0.2.8", default-features = false, features = ["yaml"] }
image = { version = "0.25.5", default-features = false, features = ["avif", "gif", "jpeg", "png", "webp"] }
jiff = { version = "0.1.14", default-features = false, features = ["alloc", "std"] }
pulldown-cmark = { version = "0.12.2", default-features = false, features = ["html", "simd"] }
rquickjs = { version = "0.8.0", features = ["parallel", "rust-alloc"] }
same-file = "1.0.6"
serde = "1.0.215"
syntect = { version = "5.2.0", default-features = false, features = ["default-syntaxes", "default-themes", "html", "regex-onig"] }
toml_edit = { version = "0.22.22", default-features = false, features = ["parse", "serde"] }

[lints]
workspace = true
