[package]
name = "ssg"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
description = "Static site generator for my personal website"
readme = "README.md"
repository.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
gray_matter = { version = "0.2.8", default-features = false, features = ["yaml"] }
jiff = { version = "0.1.14", default-features = false, features = ["alloc", "std"] }
pulldown-cmark = { version = "0.12.2", default-features = false }
rquickjs = { version = "0.8.0", features = ["parallel", "rust-alloc"] }
serde = "1.0.215"
syntect = { version = "5.2.0", default-features = false, features = ["default-syntaxes", "default-themes", "html", "regex-onig"] }

[lints]
workspace = true
